### ISSUE TITLE
the windows bar not showing

### ISSUE THREAD

**Issue by alavaelian** [edeproject/ede#2]
the windows bar with the close and minimize button is not showing i dont know whym i use arch btw i installed ede with aur

**Comment by sanel** [comment]
Thank you for report. Can you upload a screenshot please?

**Comment by alavaelian** [comment]
![2022-03-15_00-17](https://user-images.githubusercontent.com/20959812/158311935-bbca5aa1-34b7-4c52-85d6-79b674932bf1.png)

**Comment by sanel** [comment]
From what I can see, it was started without pekwm (window manager); maybe it crashed on startup. Can you, while with running EDE, try to open terminal and run `pekwm`? If it crashes, it will dump a core, so please do this:

```sh
# try to run it
$ pekwm

# maybe it crashes here, dumping "core" file on some location. Run "gdb" with these arguments:
$ gdb  /absolute/path/to/pekwm  /absolute/path/to/core
(gdb)  bt          # <--- type "bt" and press enter

# you'll get full stacktrace and copy-paste it here
```

**Comment by alavaelian** [comment]
sorry man it seem i dont have installed pekwm in my arch, y mean when i try to install it game me a confict package whit the ede one of aur

**Comment by alavaelian** [comment]
i will try installing ede from source myself, any advice ? and resources ? thanks

**Comment by sanel** [comment]
Great!
